name: FactionsX
main: gg.revival.factions.FP
version: 1.0.0
author: johnsama
description: Factions engine for Revival
depends: [MongoBukkitDriver]
commands:
  faction:
    description: Core Faction Command
    aliases: [f, t, team]
  balance:
    description: Economy Command
    aliases: [bal, money, cash]
  pay:
    description: Economy Command