database:
  enabled: false
  hostname: 'localhost'
  port: 27017
  use-creds:
    enabled: false
    username: username
    password: password
    database: 'factions'
timers:
  rename-cooldown: 300
  disband-cooldown: 300
  map-cooldown: 15
  home-warmup: 5
  stuck-warmup: 60
chat-channels:
  create:
    min-name-length: 2
    max-name-length: 10
factions:
  dtr:
    regen-time: 60
    freeze-time: 3600
    player-value: 0.6
    max-dtr: 5.5
  create:
    min-name-length: 3
    max-name-length: 16
  limits:
    max-faction-size: 20
    max-home-height: 150
    home-too-high-price: 100
    stuck-warmup: 60
  map-setup:
    warzone-radius: 1000
    nether-warzone-radius: 200
    buildable-warzone-radius: 150
    warzone-name: '&cWarzone'
    wilderness-name: '&2Wilderness'
    nether-name: '&4The Nether'
    nether-warzone-name: '&4Nether Warzone'
    end-name: '&5The End'
  claiming:
    minimum-claim-size: 10
    claim-buffer: 5
    pillar-height: 30.0
  alliances:
    enabled: true
    ally-limit: 1
    only-warn-when-visable: true
  subclaims:
    gui-title: '&0Subclaim Editor'
custom-items:
  faction-claiming-stick:
    display-name: '&aFaction Claiming Stick'
    description:
      - 'This is line 1'
      - 'This is line 2'
      - 'This is line 3'